spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:urlIdentifier
    driverClassName: org.h2.Driver
    username: test
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

debug: false